set-option -g status "on"
set -g status-interval 2

set-option -g status-fg "#d4be98"
set-option -g status-bg "#282828"
set-option -g status-style fg="#d4be98",bg="#282828",default
set-option -g mode-style fg="#d8a657",bg="#504945"

set-window-option -g window-status-style fg="#928374",bg="#282828"
set-window-option -g window-status-activity-style bg="#3c3836",fg="#d4be98"
set-window-option -g window-status-current-style fg="#1d2021",bg="#d8a657"

set-option -g pane-border-style fg="#3c3836"
set-option -g pane-active-border-style fg="#d8a657"
set-option -g display-panes-active-colour "#d8a657"
set-option -g display-panes-colour "#d8a657"

set-option -g message-style fg="#ea6962",bg="#282828"
set-option -g message-command-style fg="#d4be98",bg="#3c3836"

set-window-option -g clock-mode-colour "#d8a657"
set-window-option -g window-status-bell-style fg="#282828",bg="#ea6962"

set-option -g status-left-style none
set -g status-left-length 60
set -g status-right-style none
set -g status-right-length 150
set -g status-left '#[fg=#1d2021,bg=#d8a657,bold] #S #[fg=#d8a657,bg=#504945,nobold]#[fg=#d4be98,bg=#504945,bold] #(whoami) #[fg=#504945,bg=#282828,nobold]'
set -g status-right '#[fg=#504945,bg=#282828]#[fg=#d4be98,bg=#504945] #[fg=#d4be98,bg=#504945]%Y-%m-%d  %H:%M #[fg=#7daea3,bg=#504945,bold]#[fg=#1d2021,bg=#7daea3,bold] #h '
set -g window-status-separator '#[fg=#504945,bg=#282828]'
set -g window-status-format "#[fg=#928374,bg=#282828] #I  #[fg=#928374,bg=#282828]#W "
set -g window-status-current-format "#[fg=#282828,bg=#d8a657]#[fg=#1d2021,bg=#d8a657] #I  #[fg=#1d2021,bg=#d8a657,bold]#W #[fg=#d8a657,bg=#282828,nobold]"
