#!/bin/bash

options=(
    style=round
    width=5.0
    hidpi=off
    active_color=0xff0099ff     # client.focused border
    inactive_color=0xff2f3d44   # unfocused/inactive border
    background_color=0xff2b2c2b # matches client.background
)

borders "${options[@]}"
