-- [nfnl] fnl/config/init.fnl
require("config.trust")
require("config.autocmds")
require("config.clojure")
require("config.opts")
require("config.keymaps")
require("config.renamer")
require("config.lsp_info")
require("config.rust")
return require("config.repl_picker")
