# Gruvbox Material Dark

[main]
font=JetBrains Mono:size=13
width=50
lines=10
horizontal-pad=16
vertical-pad=12
inner-pad=8
prompt=
placeholder=Procurar...
icons-enabled=yes
match-mode=fzf
fields=filename,name,generic,keywords

[colors]
background=282828ff
text=d4be98ff
match=d3869bff
selection=3c3836ff
selection-text=d4be98ff
selection-match=d3869bff
border=7daea3ff
input=d4be98ff

[border]
width=2
radius=8

[key-bindings]
# padrão do fuzzel — sem overrides necessários
